<a href="https://colab.research.google.com/github/Dave-oo-Dave/Dave-oo-Dave.github.io/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Properties 



#Arrays

In [45]:
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)
print (a.ndim,a.shape,a.dtype)

2 (3, 3) float32


#Only ONES


In [46]:
np.ones((3,5),dtype=np.float32)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

#Only Zeros

In [47]:
np.zeros((6,2),dtype=np.int8)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

# Array RANGE

In [48]:
np.arange(1334,1338)

array([1334, 1335, 1336, 1337])

# Concatenate with AXIS


In [49]:
A=np.ones((4,1))
B=np.zeros((4,2))
np.concatenate([A,B], axis=1)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

#LIKE A


In [50]:
a= np.ones((3,3,4))
b=np.zeros_like(a)
print (b.shape)

(3, 3, 4)


#SHAPING

In [51]:
a=np.array([1,2,3,4,5,6])

a.reshape(3,2)

a.reshape(2,-1)

a.ravel()



array([1, 2, 3, 4, 5, 6])

#Transposition

In [52]:
a=np.arange(10).reshape(5,2)

In [53]:
a.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [54]:
a.transpose((1,0))

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

#Image Savings and Loadings

In [55]:
np.savez

<function numpy.savez(file, *args, **kwds)>

#Image Arrays

#Mathematical ARRAYS

In [56]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)

In [57]:
np.sqrt(a)

array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898],
       [2.6457512, 2.828427 , 3.       ]], dtype=float32)

#Indexing

In [62]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)
a[:,0]#first column (many entries)


array([1., 4., 7.], dtype=float32)

In [61]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)
a[0,-1]#firstrowlastcolumn

3.0

In [60]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)
a[0,0]#topleftelement

1.0

In [59]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)
a[0,:]#firstrow (many entries)

array([1., 2., 3.], dtype=float32)

#Sum

In [63]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)
a.sum()

45.0

In [64]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)
a.sum(axis=0)#sumoverrows

array([12., 15., 18.], dtype=float32)

In [65]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)
a.sum(axis=1)#sumovercolumns

array([ 6., 15., 24.], dtype=float32)

In [67]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float32)
a.sum(axis=1, keepdims=True)

array([[ 6.],
       [15.],
       [24.]], dtype=float32)